[package]
name = "afftree"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx = "1.0.115"
rand = "0.8.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
